apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qt3lt0r8d-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qt3lt0r8d-go 
  name: qt3lt0r8d-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qt3lt0r8d-go 
